### ISSUE TITLE
The original 3D models and rendering tools?

### ISSUE THREAD

**Issue by MultiPath** [vsitzmann/scene-representation-networks#2]
Hi,

Is it also possible to release the original 3D models (e.g. Shapenet chairs) as well as the rendering tools/scripts to generate the training images so that we can also generate new data in the same format by ourselves?

Thanks

**Comment by vsitzmann** [comment]
Hi,

the original 3D models can be downloaded for free on the [Shapenet website.](https://www.shapenet.org/)

I'll look into publishing the rendering code - until then, my code is based on [this code](https://github.com/panmari/stanford-shapenet-renderer).

Best
Vincent
