### ISSUE TITLE
Can you upload the trained model

### ISSUE THREAD

**Issue by phongnhhn92** [vsitzmann/scene-representation-networks#3]
Hello,
I have read the paper and I have found that your model requires at least 48GB of memory to train with RTX 6000 GPU. Is that possible to upload the trained model for cars or chairs dataset ? 
Thanks !

**Comment by vsitzmann** [comment]
Currently training (old checkpoints were incompatible after refactoring) & coming soon!

**Comment by vsitzmann** [comment]
While the models have to train for a bit more, I've uploaded the current status (~180k iterations in): https://drive.google.com/open?id=1IdOywOSLuK6WlkO5_h-ykr3ubeY9eDig

I'll update the models with the final ones once they're done training!
