### ISSUE TITLE
Intrinsic for custom images

### ISSUE THREAD

**Issue by feem1** [vsitzmann/scene-representation-networks#6]
Hello I love what you have built and would like to get camera intrinsically for my own images. Would you kindly tell me how to generate them for custom images?

**Comment by vsitzmann** [comment]
Please take a look at [Colmap](https://colmap.github.io/tutorial.html). Colmap has a "sparse bundle adjustment" mode, where it recovers camera extrinsics and intrinsics. Please also check out the Readme of [DeepVoxels](https://github.com/vsitzmann/deepvoxels), where I briefly discuss Colmap.
