### ISSUE TITLE
Few shot learning is currently crashing

### ISSUE THREAD

**Issue by krtkrj** [vsitzmann/scene-representation-networks#7]
Hello, keep up the great work! I am trying to replicate your results in the paper using few shot learning and the pre trained model given, but I believe the config file is not updated and it crashes due to no validation route specified and there is no parameter called specific samples. Some of the values are in string format when it should be integer. Override embedding crashes due to a parameter not found. Unable to fine tune because Freeze networks crashes. 

Thanks for your help. Love your work

**Comment by vsitzmann** [comment]
Thanks, it's fixed!
