### ISSUE TITLE
specific_observation_idcs option format

### ISSUE THREAD

**Issue by ebartrum** [vsitzmann/scene-representation-networks#9]
Hey,
For comparison purposes, I need to evaluate the reconstruction quality of this network on a specific output view from one specific input view, of each object (ie single image reconstruction). It looks as though the specific_observation_idcs option may be the right way to achieve this? Could you share an example file for this option so I can see the format? I'm assuming it specifies an input id and output id for each object.
Thanks!

**Comment by vsitzmann** [comment]
Dear Ed,

there is several ways to go about this.

It sounds like the easiest one for you would be: Make a new little dataset with the same directory structure as the original datasets, i.e.:

dataset_root/
       object_id/
              pose/
              rgb/
              intrinsics.txt

But this time, each directory only contains a single input view. You can then simply run one-shot learning using this dataset with your previously trained checkpoint (as discussed in the other issue) - you *don't* need to use the specific_observation_idcs in this case. I created that CLI parameter for the case where you have many views for each object (like what is the case in the test set) but  you only want to use a single one of them to reconstruct the object. 

Hope that helps!

**Comment by ebartrum** [comment]
Thanks, it works!

**Comment by vsitzmann** [comment]
I'm glad!
